### ISSUE TITLE
Format longevity, flexibility and metadata

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon2#2]
OK, so I have a bold suggestion, that I'd like to put out there. Since we're talking about validation methods and specification of the janno-format, I thought why not using a CSV-on-the-web style metadata-description file in JSON? This would
1. make the meta-data description properly standardised (i.e. author, maintainer, last update, ...)
2. define the columns of the janno file, including constraints like "String_Choice" or "nonNegativeInteger".
3. allow users to leave out columns if they don't need them.
4. Allow us to extend the format later. Previous datasets would still be valid, given that their metadata-file describes all columns correctly
5. Possibly facilitate validation

This is all very similar to my plans with Poseidon3. In fact, it's so similar that I think it's actually almost there, except that I had planned to go for a multi-file format (a sites table, an individual table, ...). But I actually think that's a detail that we don't need in the beginning. In fact, it would make implementation hell of a lot easier than this complex relational structure that I had in mind for that. It's actually much simpler to go with the one-file schema that we have. And in fact, our packages are already in that format. 

Here is a rather small and minimal example for a janno file with only the first three columns (which would only be allowed if we declare no other column to be required:

```JSON
{
  "@context": ["http://www.w3.org/ns/csvw"],
  "dc:description": "Genetic data published in Schiffels et al. 2016",
  "dc:conformsTo": "http://w3id.org/poseidon/v2.1/terms.rdf.jsonld#PackageInfo",
  "dc:title": "Schiffels_2016",
  "dc:contributor": {
    "dc:name" : "Stephan Schiffels",
    "dc:email" : "stephan.schiffels@institute.org"
  },
  "dc:modified": {"@value": "2020-02-28", "@type": "date"},
  "dc:license" : "CC-BY",
  "dc:source" : "sources.bib",
  "dc:references" : {
    "@type" : "http://w3id.org/poseidon/v2.1/terms.rdf.jsonld#GenotypeFileSpecification",
    "@value" : {
      "http://w3id.org/poseidon/terms.rdf.jsonld#GenotypeDataFormat" : "PLINK",
      "http://w3id.org/poseidon/terms.rdf.jsonld#GenotypeGenoFile" : "Schiffels_2016.bed",
      "http://w3id.org/poseidon/terms.rdf.jsonld#GenotypeSnpFile" : "Schiffels_2016.bim",
      "http://w3id.org/poseidon/terms.rdf.jsonld#GenotypeIndFile" : "Schiffels_2016.fam"
    }
  },
  "tables": [{
    "url" : "Schiffels_2016.janno",
    "tableSchema" : {
      "columns" : [{
        "name": "Individual_ID",
        "datatype": "string",
        "dc:description": "from Pandora or external labs, in most cases Individual, but can also be Sample or Library depending on the granularity of the project. This doesn't follow a strict format but should just be a unique string that identifies the individual within the wider Poseidon v2 dataset. It can be Pandora IDs or Boston IDs or others.	Examples: NYI001	RK1001	I0063",
        "required": true
      }, {
        "name": "Collection_ID",
        "datatype": "string",
        "dc:description": "Archaeological_ID as in Pandora, ideally, or other datasets. Spaces allowed. For modern samples, report additional collection_ID or 'n/a'. Examples:	Sk224	kurgan 2, grave 1	n/a"
      }, {
        "name": "Source_Tissue",
        "datatype": "string",
        "separator": ",",
        "dc:description": "comma-separated (no spaces) in case libraries from multiple skeletal/tissue/source elements have been merged. Examples:	Petrous,Tooth	Coprolite"
      }]
    }
  }] 
}
```

The complete schema is of course much longer. I just went through our janno-definition file and converted that to a full CSVW JSON file (which I'll upload to a new `discussion` folder in this repo). To keep things simple for the user, I imagine that we provide the default and full schema, with version, somewhere online, so that users who just want to write out the full janno-table (as we have done now on our cluster) can simply write:

```JSON
{
  "@context": ["http://www.w3.org/ns/csvw"],
  "dc:description": "Genetic data published in Schiffels et al. 2016",
  "dc:conformsTo": "http://w3id.org/poseidon/v2.1/terms.rdf.jsonld#PackageInfo",
  "dc:title": "Schiffels_2016",
  "dc:contributor": {
    "dc:name" : "Stephan Schiffels",
    "dc:email" : "stephan.schiffels@institute.org"
  },
  "dc:modified": {"@value": "2020-02-28", "@type": "date"},
  "dc:license" : "CC-BY",
  "dc:source" : "sources.bib",
  "dc:references" : {
    "@type" : "http://w3id.org/poseidon/v2.1/terms.rdf.jsonld#GenotypeFileSpecification",
    "@value" : {
      "http://w3id.org/poseidon/terms.rdf.jsonld#GenotypeDataFormat" : "PLINK",
      "http://w3id.org/poseidon/terms.rdf.jsonld#GenotypeGenoFile" : "Schiffels_2016.bed",
      "http://w3id.org/poseidon/terms.rdf.jsonld#GenotypeSnpFile" : "Schiffels_2016.bim",
      "http://w3id.org/poseidon/terms.rdf.jsonld#GenotypeIndFile" : "Schiffels_2016.fam"
    }
  },
  "tables": [{
    "url" : "Schiffels_2016.janno",
    "tableSchema" : "https://w3id.org/poseidon/v2.1/janno-schema.json"
  }]
}
```

Note that in my suggestion here, I also propose to refer to a `sources.bib` file to include bibliographic information about the publication(s) of that data. And I refer to the genotype files, which can also be nicely specified in the meta-data file.

How about validation?

Well, in a python implementation we could use Robert Forkel's CSVW package to validate at least the provided janno-file against the provided meta-data file. But that of course wouldn't yet guarantee that it's a valid Poseidon dataset. So I think we have to implement some kind of additional validation of the metadata-file, so that we make sure it contains all the relevant columns. For example, we would through an error if someone would provide a CSVW dataset with an `Individual_ID` column, even if the dataset itself is valid CSVW.

**Comment by stschiff** [comment]
OK, I've added the full janno.json file as converted from our Google Docs to the `discussion` folder. Note that I'm aware that implementing parsing and validating this is quite some work, and I'm not suggesting our initial implementation needs to be able to do it. BUT: We currently have no coherent and structured way to store metadata in Poseison2 (contributor, email, ...), which would be solved by this. Also, implementing a validator on the current janno-format is also quite some work. If one has a CSVW parser, then I would think that it is not harder to write a validator for CSVW-structured data. A question is whether there is a CSVW parser in R. 

In any case, as I said, we don't have to do all that right away, I thought I just share this idea so that we can come back to it.

I'm seriously considering diverting my Poseison3 efforts to this new idea. I could reuse the bits that I've already implemented, using Pythons CSVW library and validating that instead of the janno-file directly.

**Comment by nevrome** [comment]
Hm... ok. I recognize a good infiltration if I see one :smile: 
The Idea is great and I think we should go forward with merging poseidon2 with poseidon3. poseidon2 lacks elegance and poseidon3 lacks existence. 

I worry about the following things:

1. This .json file is seriously scary. We should have a generator module that creates this monstrosity from the simple .tsv janno file.
2. How does the validation in Robert Forkel's CSVW package work? Ideally we don't want a validator that simply rejects, but which informs about each cell-wise (not just column wise!) mistake. It should show every mistake on the first run, not just the first  one to cause an error. 
3. The language mess between R, Python and Haskell.

**Comment by stschiff** [comment]
All good points. I mean, there is also a serious option of not going the route of CSVW and simply define our own metadata-description format that is much simpler. We can also take the CSVW stuff as a future export functionality... so someone who wants CSV on the web can get it, but it's not the default format? You're right that it's a bit scary to write.

With respect to validation, that's something I was never fully happy with in the whole Poseidon3 endeavour: Robert's package validates only the CSVW aspect. But in order to validate this into a valid Poseidon-module, we then need to validate on top of CSVW, which is weird and feels strange. Because CSVW is made for maximum flexibility, but Poseidon imposes some constraints (some columns are required, the datatypes can't be set arbitrarily, we may require certain meta-data fields like "dc:contributor" and so on) any validation then operates on an abstract layer after the CSVW parsing. 

Perhaps you're right and we should simply stick with the simplest way we can define our package, without much overhead or additional flexibility...

A more basic JSON metadata-file without respecting CSVW could perhaps look like this:

```JSON
{
  "description": "Genetic data published in Schiffels et al. 2016",
  "title": "Schiffels_2016",
  "contributor": "Stephan Schiffels",
  "email" : "stephan.schiffels@institute.org",
  "last_modified": "2020-02-28",
  "bib_file" : "sources.bib",
  "geno-format" : "PLINK",
  "geno-file": "Schiffels_2016.bed",
  "snp-file": "Schiffels_2016.bim",
  "ind-file": "Schiffels_2016.fam",
  "janno-file": "Schiffels_2016.janno",
  "janna-version": "v2.1"
}
```

And we would require some of these fields, but not others. And the Janno-Format itself is fixed, with all columns always explicitly filled, if need be with "N/A".

What do you think?

**Comment by stschiff** [comment]
And we would of course offer to generate that JSON automatically, e.g. using
```
janno-tools init --geno-file=Schiffels_2016.bed --snp-file=Schiffels_2016.bim \
   --ind-file=Schiffels_2016.fam --geno-format=PLINK --contributor="Stephan Schiffels" \
   --email="schiffels@institute.org" --bib-file=sources.bib
```

or so?

**Comment by nevrome** [comment]
I think I get it now. CSVW can not be enough for us, because we have to consider validation of non-tabular data (.bim/.bed/.fam) as well. CSVW would only be relevant for the context data in the .janno file. 

What do we gain with CSVW? Entrance to the LOD world? Couldn't we just generate these things fully automatically when there is a serious demand?

I agree that we need a sources.bib file and a metadata file as part of the poseidon2 package structure. But does this metadata file have to be .json?

**Comment by stschiff** [comment]
OK, so to conclude a short discussion we had, the minimal metadata-format above would be a good starting point. Perhaps we can extend the format to YAML and not just JSON, so it can be more succinctly written as:

```YAML
title: Schiffels_2016 #Required
description: Genetic data published in Schiffels et al. 2016 #Required
contributor: #Required
  name: Stephan Schiffels
  email: stephan.schiffels@institute.org
lastModified: 2020-02-28 #Required
bibFile: sources.bib #Optional
genotypeData: #Required
  format: PLINK
  genoFile: Schiffels_2016.bed
  snpFile: Schiffels_2016.bim
  indFile: Schiffels_2016.fam
janno: #Required
  file: Schiffels_2016.janno
  version": v2.1
```
Here I have also imposed a bit more structure with nested objects (`contributor`, `genotypeData` and `janno`) as a suggestion. Also I suggest camelCase throughout.

**Comment by stschiff** [comment]
I think we can close this. Hope that's OK. Reopen if you feel like.
