### ISSUE TITLE
IDs

### ISSUE THREAD

**Issue by yesdavid** [poseidon-framework/poseidon2#30]
It would be nice if the ids of the dates could be provided for poseidonR::quickcalibrate(), just like in Bchron::BchronCalibrate(), to have them included in the output data frame.

**Comment by nevrome** [comment]
Can't you just `cbind` the ID's of the input data to the output of quickcalibrate? I would rather not edit `quickcalibrate`, because it's designed for a very specific purpose within the Poseidon framework, not as a general-purpose calibration function.

**Comment by yesdavid** [comment]
if the order of the dates is the same, yes
